### ISSUE TITLE
Question about "Ancestry Pulses(option -p)"

### ISSUE THREAD

**Issue by Yuki0925** [russcd/Ancestry_HMM#18]
Hi,
I have two questions about "Ancestry Pulses(option -p)."

The first is a simple question. What is the unit of measure for [int, time before present]?" It says "the time before the present (in generations)" so I would expect it to be generations. For example, in the case of humans, if each generation is 20 years, is it correct to say that 10,000 years ago was 500 generations ago? I asked this question to confirm because I thought that the unit of measurement in other papers is not generation.

Second question. I am not certain when to put the number in [int, time before present]. I plan to use a single pulse model with two ancestral populations. These two populations experienced admixture 3000 years ago. What other information do you need to find the numbers?

I am a student and very interested in this approach. I would be very happy if you could help me.
Thanks!

**Comment by russcd** [comment]
Hi Yuki, 

The unit of measurement is generations. In your case, 500 generations would correct. 

The way you could specify a single pulse model is something like this:

If m0 is the proportion of ancestry from ancestral population 0, and m1 is the portion from ancestral population 1. In a single pulse model, m0 = 1 - m1. Generations before present is g. Then:

ancestry_hmm -i <panel_file> -s <ploidy_file> -a 2 m0 m1 -p 0 100000 0.5 -p 1 g 0.5. 

If you want to estimate the time since admixture and provide an initial guess of g generations, you would specify the number of generations as a negative value, -g: 

ancestry_hmm -i <panel_file> -s <ploidy_file> -a 2 m0 m1 -p 0 100000 0.5 -p 1 -g 0.5. 

Does that answer your question?

**Comment by Yuki0925** [comment]
Hi,thank you for answering the first question.
I would like to ask you to confirm something on the second question.
I write the following code.
` ancestry_hmm -i [input_file] -s [sample_file] -a m0 m1 -p 0 g0 M0 -p 1 g1 M1`

#m0,m1,M0,M1,g0,g1 are arbitrary numbers
#(m0)+(m1)=1

Question
1. If the admixed generation is known, should I put the admixed generation in g1 instead of a negative value?
2. What number to put in g0? I would expect the p0 population to be the generation that differentiated the p0 population from the other populations.
Thanks!
