### ISSUE TITLE
Posterior nan values on small sample

### ISSUE THREAD

**Issue by kaseykhanhpham** [russcd/Ancestry_HMM#19]
Hi there - I am getting all "nan" values in the posterior file outputs from my runs of Ancestry_HMM. Unlike in Madhartmann1's case, my dataset is fairly small -- two panels of 10 samples each and 20 samples to estimate ancestry (all diploid). I've been using the following parameters:

`ancestry_hmm -i all_ahmm_in.tab -s sample_ploidy.txt -a 2 0.98 0.02 -p 0 100000 0.98 -p 1 -1700 0.02 -g`

I can send my input file for debugging if necessary.

Thanks for your help!

**Comment by russcd** [comment]
Hi Kasey, 

Yes, please send me an example file and I will get back to you ASAP.

**Comment by zzzygolden** [comment]
> Hi Kasey,
> 
> Yes, please send me an example file and I will get back to you ASAP.

Hi russcd,
I also got all "nan" in my posteriors' output. My situation was similar to kaseykhanhpham's: two reference parents of 11 samples and 5 samples for estimating ancestry, all diploid too. I want to know the reason leading to such results and how to solve this as I have other samples to test lately.

**Comment by russcd** [comment]
Hi zzzygolden, 

Can you send me a minimal input file and command line that reproduces this bug?

Thanks

**Comment by zzzygolden** [comment]
Hi russcd,


My input file and command line are in attachment.


Thanks.






zengying
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "russcd/Ancestry_HMM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月2日(星期一) 凌晨0:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [russcd/Ancestry_HMM] Posterior nan values on small sample (Issue #19)





 
Hi zzzygolden,
 
Can you send me a minimal input file and command line that reproduces this bug?
 
Thanks
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

ND_AHMM_INPUTFILE (61.77M, 2023年11月01日 12:35 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=7e383064faab41cc463889021434501f404c0301020d5654150f0552031901055c081d000552571d0d09050206055a040a0106003225627e7c67712c7f793d7976686530747d2e753805&code=880d24b0
